### ISSUE TITLE
Wrong directory path?! 

### ISSUE THREAD

**Issue by upwindanderl** [robmarkcole/HASS-Photo-browser#3]
I'm really not good in coding or even reading code but i'm not sure if the image directory path is right?!

wit the original path `  update_images: python3 /user/.homeassistant/www/generate_index.py --image_directory_path /user/.homeassistant/www/images
`
i get some error with return code 2 in the core logs

with this path `  update_images3: python3 /config/www/generate_index.py --image_directory_path /config/www/images
`
the index.html file is generated but at least not working because the images have still the wrong path dir

**Comment by robmarkcole** [comment]
The best approach is to use the terminal to `pwd` in the location you want the path for, then use whatever that gives. Thanks
